mer-packages/connman

connman/gsupplicant/dbus.c, connman/gsupplicant/supplicant.c, connman/plugins/bluetooth.c, connman/plugins/jolla-gps.c, connman/src/dnsproxy.c, connman/src/main.c, connman/src/peer.c, connman/src/rfkill.c, connman/src/rtnl.c, connman/src/technology.c
Unfreed (but still reachable) memory is cluttering valgrind report quite a bit; some of it isn't possible to remove without touching glib, but the changes in this PR alleviate the situation at least a bit. 
PR contains also a more general optimization for supplicant D-Bus calls: if there's not callback function to handle a reply from supplicant, don't bother requesting the reply in the method call.
=> Cleanup reachables on exit

connman/src/counter.c
DBusMessage message leaks memory if not cleaned when
counter is not found.
=> [connman] counter: fix possible memory leak

connman/gsupplicant/supplicant.c
Reverted the previous commit for avoiding interface removal reply as it had a bug: object path parameter was not added to the D-Bus message if there wasn't a callback function. New version adds the parameter always as it should be done.
=> Supplicant dbus refix

connman/src/ippool.c, connman/src/main.c, connman/unit/test-ippool.c
Adds TetheringSubnetBlock as supported configuration
option. TetheringSubnetBlock = 192.168.199.0 makes
ippool to start allocating blocks from 192.168.199.0.
=> [connman] configurable tethering/ippool starting subnet

connman/src/service.c
Otherwise it could be deallocated by __connman_network_disconnect meaning that all subsequent references to it will access freed memory.
=> __connman_service_disconnect needs to hold a reference to the service

connman/plugins/ofono.c, connman/src/wispr.c
This prevents connman from calling disconnect before connect is finished and generally calms the whole thing down.
The second wispr-related checkin is part of this pull request because for some reason fixing the ofono problem made the wispr crash occur much more often than before.
=> ofono: return -EINPROGRESS from connect/disconnect

connman/Makefile.plugins, connman/configure.ac, connman/doc/logcontrol-api.txt, connman/plugins/logcontrol.c
It provides the following methods:
```
string[] List()
void Enable(string pattern)
void Disable(string pattern)
```
Enable and Disable methods allow to modify connman logging settings without restarting it. The List method returns the list of files and aliases for which logging can be changed at runtime.
=> Add net.connman.DebugLog interface

connman/gsupplicant/supplicant.c
Sometimes wpa_supplicant reports BSS signal strength as zero or does not
send the BSS 'Signal' property at all.
As all other signal strength values are negative, a value of zero will
always be the greatest one keeping the signal value forever at zero. This
in turn translates into an eternal wifi service signal strength of 100.
Fix this by using -90 as a reasonable value for a BSS with unknown signal
strength.
Reported by Thomas Green.
=> gsupplicant: Use a reasonable value for zero BSS signal strength

connman/src/service.c
The AutoConnect property is false if Favorite is false. If Favorite
changes the value of AutoConnect is likely to change as well. This is
especially true when first connecting to a service.
=> [connman] Changes to favorite property also affect the autoconnect property

connman/gsupplicant/supplicant.c
With auth_alg set to "OPEN SHARED" some drivers (particularly bcmdhd on nexus) won't connect to open wifi access points.
=> gsupplicant: Use OPEN auth_alg for open wifi networks

connman/src/ipconfig.c
If service is ever being configured with manual ip-address, netmask
and gateway and later changed to dhcp, the related settings must
not be read if configuration method is not manual or fixed.
Otherwise they can possible collide with the settings got from
dhcp-server if they are exactly the same
(eg. dhcp.c: lease_available_cb()). This could lead network
interface not being configured correctly.
=> [connman] ipconfig: Use only settings related to configuration method

connman/gdhcp/common.c
Some buggy dhcpv6-server implementations are re-using
the original source port from the dhcpv6-client messages
to their dhcpv6-reply packets (eg. Cisco EPC3940L) as a
destination port. Due to this we need to make sure that we
use DHCPV6_CLIENT_PORT (udp/546) as the source port when sending
client dhcpv6-messages.
=> [connman] gdhcp: Use DHCPV6_CLIENT_PORT as source port

connman/src/network.c
This is due bug in ConnMan not handling plain ipv6-connections
correctly with ipv6-only cellular-connections. Can be reverted
when the ipv6-only works correctly with _AUTO-method with ofono.
=> [connman] network: stop dhcpv6 also when method is _FIXED

connman/src/service.c
Routes should not be tried to be set with nameserver
and gw being different family, as this will lead into
having link-local routes for hosts which are not on
the link (add_nameserver_route() will add link-local route
if adding host route fails).
=> [connman] service: set routes only for same family-type

connman/src/network.c
Setting up gateway is handled by the kernel
therefore ConnMan does not need to do it
when dhcpv6 is used.
This fixes the issue with IPv6 nameserver host routes
getting added as link-local due the gateway in the
ipconfig was always null.
=> [connman] network: do not try to set gateway with dhcpv6

connman/src/dhcpv6.c, connman/src/inet.c
**inet_pton**()  returns  1  on  success (network address was successfully converted).  0 is returned if `src` does not contain a character string representing a valid network address in the specified address family.  If `af` does not contain a valid address family,  -1  is  returned  and `errno` is set to **EAFNOSUPPORT**.
=> Fixed the check of inet_pton return value

connman/src/network.c
```
==7180== 806 (208 direct, 598 indirect) bytes in 26 blocks are definitely lost in loss record 190 of 199
==7180==    at 0x483933C: malloc (vg_replace_malloc.c:296)
==7180==    by 0x48B7543: g_malloc (gmem.c:104)
==7180==    by 0x48D3E1F: g_slice_alloc (gslice.c:1016)
==7180==    by 0x48D4CDB: g_slist_prepend (gslist.c:267)
==7180==    by 0x5BF0F: __connman_inet_ipv6_get_prefixes (inet.c:2052)
==7180==    by 0x3F32B: check_dhcpv6 (network.c:499)
==7180==    by 0x58C13: icmpv6_recv (inet.c:1356)
==7180==    by 0x59357: icmpv6_event (inet.c:1372)
==7180==    by 0x59357: icmpv6_event (inet.c:1362)
==7180==    by 0x490BBB7: g_io_unix_dispatch (giounix.c:167)
==7180==    by 0x48AFB1F: g_main_dispatch (gmain.c:3066)
==7180==    by 0x48AFB1F: g_main_context_dispatch (gmain.c:3642)
==7180== …
```
=> Fix memory leak in check_dhcpv6

connman/src/dnsproxy.c
The ones received over UDP didn't have it, which resulted in something like this:
```
==7180== Syscall param socketcall.sendto(msg) points to unaddressable byte(s)
==7180==    at 0x4B9CE34: sendto (in /lib/libc-2.15.so)
==7180==    by 0x79283: ns_resolv (dnsproxy.c:1644)
==7180==    by 0x7977F: resolv (dnsproxy.c:2648)
==7180==    by 0x7C80F: __connman_dnsproxy_flush (dnsproxy.c:2770)
==7180==    by 0x47C37: update_nameservers (service.c:1158)
==7180==    by 0x47F27: __connman_service_nameserver_remove (service.c:1275)
==7180==    by 0x5D87B: dhcp_invalidate (dhcp.c:133)
==7180==    by 0x5E677: __connman_dhcp_stop (dhcp.c:641)
==7180==    by 0x3F9CB: set_disconnected (network.c:746)
==7180==    by 0x4079B: connman_network_set_connected (network.c:1465)
==7180==    by 0x21563: …
```
=> dnsproxy: request_data in request_list need the request data

connman/src/wispr.c
wp_context is deallocated by `portal_manage_status` and can't be used after that. The problem is detected by valgrind as follows:
```
==23718== Invalid read of size 4
==23718==    at 0x735EC: wispr_portal_web_result (wispr.c:785)
==23718==    by 0x1B58B: call_result_func (gweb.c:460)
==23718==    by 0x1B58B: received_data (gweb.c:896)
==23718==    by 0x48AFB85: g_main_dispatch (gmain.c:3066)
==23718==    by 0x48AFB85: g_main_context_dispatch (gmain.c:3642)
==23718==    by 0x48AFE11: g_main_context_iterate.isra.5 (gmain.c:3713)
==23718==    by 0x48B01D3: g_main_loop_run (gmain.c:3907)
==23718==    by 0x149D3: main (main.c:761)
==23718==  Address 0x50ca0b8 is 0 bytes inside a block of size 100 free'd
==23718==    at 0x4840ABC: free (vg_replace_malloc.c:473)
==23718==    by 0x7347B: …
```
=> Fix crash in wispr_portal_web_result

connman/src/agent.c
The way it was done, leaked all the elements from the list *before* the one being removed:
```
==15760== 4,936 (12 direct, 4,924 indirect) bytes in 1 blocks are definitely lost in loss record 232 of 234
==15760==    at 0x483933C: malloc (vg_replace_malloc.c:296)
==15760==    by 0x48B7543: g_malloc (gmem.c:104)
==15760==    by 0x48D3E1F: g_slice_alloc (gslice.c:1016)
==15760==    by 0x48AB343: g_list_append (glist.c:232)
==15760==    by 0x51567: connman_agent_queue_message (agent.c:250)
==15760==    by 0x50803: __connman_agent_request_passphrase_input (agent-connman.c:483)
==15760==    by 0x4A21F: __connman_service_connect (service.c:6463)
==15760==    by 0x4AA0B: auto_connect_service (service.c:4004)
==15760==    by 0x4AB23: run_auto_connect (service.c:4027)
==15760==    by 0x48B0BE3: …
```
=> Fix incorrect removal of elements from a double-linked list

connman/gsupplicant/supplicant.c
```
==13796== 5,544 (1,848 direct, 3,696 indirect) bytes in 22 blocks are definitely lost in loss record 219 of 222
==13796==    at 0x483933C: malloc (vg_replace_malloc.c:296)
==13796==    by 0x48B778F: g_try_malloc0 (gmem.c:280)
==13796==    by 0x25C0B: interface_network_added (supplicant.c:1157)
==13796==    by 0x260EF: interface_property (supplicant.c:1906)
==13796==    by 0x286FF: supplicant_dbus_property_foreach (dbus.c:145)
==13796==    by 0x2245F: g_supplicant_filter (supplicant.c:2636)
==13796==    by 0x497AF4F: dbus_connection_dispatch (in /usr/lib/libdbus-1.so.3.7.12)
==13796==    by 0x8164F: message_dispatch (mainloop.c:72)
==13796==    by 0x48ABA8B: g_idle_dispatch (gmain.c:5251)
==13796==    by 0x48AFB1F: g_main_dispatch (gmain.c:3066)
==13796==    by 0x48AFB1F: …
```
=> Fixed memory leak in supplicant.c

connman/Makefile.plugins, connman/configure.ac, connman/plugins/jolla-usb.c, rpm/connman.spec
The "USB gadget" thing provided by upstream isn't suitable for USB tethering. Particularly, there's no need to register network driver for the USB interface (and therefore bother with IP configuration and such). This plugin does the bare minimum to register "usb gadget" technology for which tethering can be enabled. And it actually works.
=> USB tethering plugin

connman/src/device.c, connman/src/main.c
connman brings down managed interfaces at startup. Sometimes it's unnecessary or even harmful. `DontBringDownAtStartup` list in `main.conf` allows to make exceptions for some interfaces (such as `rndis0`).
=> Add configurable DontBringDownAtStartup list

connman/plugins/wifi.c
Sometimes it is possible connection to be left in "associating"-state
after receiving multiple deauth-messages from access point.
Therefore disconnect after 10 seconds unless we have not reached
connected/disconnected-state.
=> [connman] wifi: disconnect if connections seems to be stuck. MER#930

connman/plugins/wifi.c
While wifi->state is G_SUPPLICANT_STATE_COMPLETED and gets changed into
G_SUPPLICANT_STATE_4WAY_HANDSHAKE the connection is most probably roaming.
However if for some reason the wifi->state changes into
G_SUPPLICANT_STATE_DISCONNECTED after being G_SUPPLICANT_STATE_4WAY_HANDSHAKE
the handle_4way_handshake_failure() is called from interface_state() it is
required to check wifi->connected and force disconnect if true.
If not the actual disconnection will be skipped unless
retries > FAVORITE_MAXIMUM_RETRIES and wifi->connected will be set as false.
Later on this will cause state-machine deadlock between network.c and wifi.c
as network.c will still think that the network is connected and after wifi.c
thinks it's not.
In short: wifi->state will change into G_SUPPLICANT_STATE_SCANNING-> …
=> [connman] wifi: disconnect if 4way-handshake fails while roaming. MER#930

connman/plugins/wifi.c
This does not make any sense and does not exists in the upstream either.
=> [connman] revert disabling scanning while associating. MER#955

connman/plugins/wifi.c
It's possible from wpa_s to change the state from completed to scanning
without going through disconnected state if interface signals that the carrier
went off and on (IFF_LOWER_UP flag).
This will cause dead lock similar in e770b6e05f48922ef76b5b150de26c26949910ae
if the wifi gets into associating state as the network->connected is still true
but wifi->connected is not.
=> [connman] wifi: disconnect if wpa_s state changes from completed to scanning. MER#930

connman/plugins/ofono.c
`modem_update_interfaces()` would crash if `"org.ofono.ConnectionManager"` interface is removed right after it has been added, before `GetContext` call completes (or if it fails):
```
connmand[5141]: plugins/ofono.c:modem_changed() /ril_0 Interfaces 0x05
connmand[5141]: plugins/ofono.c:modem_update_interfaces() /ril_0
connmand[5141]: plugins/ofono.c:api_added() cm added
connmand[5141]: plugins/ofono.c:get_properties() /ril_0 path /ril_0 org.ofono.ConnectionManager
connmand[5141]: plugins/ofono.c:cm_get_contexts() /ril_0
connmand[5141]: plugins/ofono.c:cm_update_attached() /ril_0 Attached 1
connmand[5141]: plugins/ofono.c:modem_changed() /ril_0 Interfaces 0x01
connmand[5141]: plugins/ofono.c:modem_update_interfaces() /ril_0
connmand[5141]: plugins/ofono.c:api_removed() cm removed
==5141== …
```
=> Fix crash in modem_update_interfaces

connman/plugins/ofono.c
Otherwise connman would crash if `"org.ofono.ConnectionManager"` interface is removed while SetProperty("Active") call is pending for the connection context. First, it results in access to freed memory:
```
==2144== Invalid read of size 1
==2144==    at 0x483A114: strlen (vg_replace_strmem.c:412)
==2144==    by 0x4B0609B: vfprintf (vfprintf.c:1630)
==2144==    by 0x4BB1B6B: __vfprintf_chk (vfprintf_chk.c:35)
==2144==    by 0x4B974FB: __vsyslog_chk (syslog.c:224)
==2144==    by 0x3B42B: vsyslog (syslog.h:47)
==2144==    by 0x3B42B: connman_debug (log.c:107)
==2144==    by 0x2E49F: set_property_reply (ofono.c:382)
==2144==    by 0x498B7C7: ??? (in /usr/lib/libdbus-1.so.3.7.12)
==2144==    by 0x49775FF: ??? (in /usr/lib/libdbus-1.so.3.7.12)
==2144==    by 0x497ACAB: dbus_connection_dispatch …
```
=> Cancel pending activation when context is removed.

connman/plugins/wifi.c
This is a rebase of f338fe54ae3030dd31ad2959c3d9166ede98e9b5 to make
the fix exactly as same as in the upstream.
=> [connman] "rebase" of f338fe54ae3030dd31ad2959c3d9166ede98e9b5. MER#930

connman/src/agent-connman.c, connman/src/service.c
This is essentially two old pull requests https://github.com/mer-packages/connman/pull/211 and https://github.com/mer-packages/connman/pull/212 rolled into one. I just had the exact same problem that I though was fixed (`network->connecting` and `network->associating` are true, `network->driver` is NULL, nothing works) with very recent connman 1.24+git98. So it appears that the problem hasn't been completely fixed by any of the recent changes.
The problem reproduced itself after a sudden reboot of the access point (due to a power surge).
And yes, this PR doesn't really fix anything, it's about recovering from the above described condition. These changes haven't been accepted by upstream because *"no recovery is necessary if everything works as it's supposed to"* or something along those …
=> Drop references to dead networks

connman/plugins/jolla-signalpoll.c
Dereferencing the service may result in `signalpoll_remove_poll_service()` being called again on the same stack like this:
```
==4093== Invalid write of size 4
==4093==    at 0x40301A0: memset (mc_replace_strmem.c:1007)
==4093==    by 0x40C7414: g_slice_free1 (string3.h:84)
==4093==    by 0x40C7F94: g_slist_delete_link (gslist.c:557)
==4093==    by 0x808061C: signalpoll_remove_poll_service (jolla-signalpoll.c:139)
==4093==    by 0x80806A9: signalpoll_service_state_changed (jolla-signalpoll.c:154)
==4093==    by 0x80A5A16: __connman_notifier_service_state_changed (notifier.c:324)
==4093==    by 0x8095B98: state_changed (service.c:1510)
==4093==    by 0x809DBD3: service_indicate_state (service.c:5735)
==4093==    by 0x809E8A3: __connman_service_ipconfig_indicate_state (service.c:6224) …
```
=> signalpoll: Prevent service link from being freed twice

connman/src/service.c
Otherwise, service may stay in the `ASSOCIATION` state forever and `update_from_network()` won't do anything because `is_connecting()` keeps returning true, making recovery impossible.
These hickups are pretty hard to catch but they do happen quite often (once in a few days) in the areas with unstable wifi reception.
=> Reset state to idle when disassociating service from network

connman/include/service.h, connman/plugins/wifi.c, connman/src/service.c
When signal strength changes as a result of a poll, just update the service strength property and don't do anything else (like re-sorting the services which may have various side-effects)
=> Make signal strength polling less destructive

connman/src/timeserver.c
Upstream is unable to explain this assumption (and yet refusing to take it out)
=> Don't assume that default gateway acts as NTP server

connman/plugins/wifi.c
It seems that wpa_supplicant gets confused if we pass frequency
to scan params when trying to connect to hidden AP.
Fixes CM-676
=> [connman] wifi: Do not add frequency to hidden AP scan. MER#1252

connman/Makefile.am
Service files are not anymore generated by AC_OUTPUT, like they
used to be.
=> [connman] Fix service-files substitution. Fixes MER#1294
